**GROUP** **9**

CREDIT RISK PREDICTION

In [41]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [42]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

LOADING THE DATASET

In [43]:
df=pd.read_csv("/content/drive/MyDrive/GROUP-9(ML)/german_credit (1).csv")
df

,Checking_Status,Duration_Months,Credit_History,Purpose,Credit_Amount,Savings_Status,Employment_Since,Installment_Rate,Personal_Status_Sex,Other_Debtors_Guarantors,...,Property,Age,Other_Installment_Plans,Housing,Existing_Credits,Job,Dependents,Telephone,Foreign_Worker,Credit_Risk
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A14,12,A32,A42,1736,A61,A74,3,A92,A101,...,A121,31,A143,A152,1,A172,1,A191,A201,1
996,A11,30,A32,A41,3857,A61,A73,4,A91,A101,...,A122,40,A143,A152,1,A174,1,A192,A201,1
997,A14,12,A32,A43,804,A61,A75,4,A93,A101,...,A123,38,A143,A152,1,A173,1,A191,A201,1
998,A11,45,A32,A43,1845,A61,A73,4,A93,A101,...,A124,23,A143,A153,1,A173,1,A192,A201,2
999,A12,45,A34,A41,4576,A62,A71,3,A93,A101,...,A123,27,A143,A152,1,A173,1,A191,A201,1

PRINTS FIRST 5 ROWS

In [44]:
df.head()

,Checking_Status,Duration_Months,Credit_History,Purpose,Credit_Amount,Savings_Status,Employment_Since,Installment_Rate,Personal_Status_Sex,Other_Debtors_Guarantors,...,Property,Age,Other_Installment_Plans,Housing,Existing_Credits,Job,Dependents,Telephone,Foreign_Worker,Credit_Risk
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

PRINTS FIRST 5 COLUMNS

In [6]:
df.tail()

,Checking_Status,Duration_Months,Credit_History,Purpose,Credit_Amount,Savings_Status,Employment_Since,Installment_Rate,Personal_Status_Sex,Other_Debtors_Guarantors,...,Property,Age,Other_Installment_Plans,Housing,Existing_Credits,Job,Dependents,Telephone,Foreign_Worker,Credit_Risk
995,A14,12,A32,A42,1736,A61,A74,3,A92,A101,...,A121,31,A143,A152,1,A172,1,A191,A201,1
996,A11,30,A32,A41,3857,A61,A73,4,A91,A101,...,A122,40,A143,A152,1,A174,1,A192,A201,1
997,A14,12,A32,A43,804,A61,A75,4,A93,A101,...,A123,38,A143,A152,1,A173,1,A191,A201,1
998,A11,45,A32,A43,1845,A61,A73,4,A93,A101,...,A124,23,A143,A153,1,A173,1,A192,A201,2
999,A12,45,A34,A41,4576,A62,A71,3,A93,A101,...,A123,27,A143,A152,1,A173,1,A191,A201,1

FINDS THE DIMENSION OF THE DATASET

In [7]:
#gives the number of rows and columns present in the dataset
df.shape

(1000, 21)

SUMMARY STATISTICS

In [8]:
#used to give statistical summary of numerical columns
df.describe()

,Duration_Months,Credit_Amount,Installment_Rate,Residence_Since,Age,Existing_Credits,Dependents,Credit_Risk
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000,1.300000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086,0.458487
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000,2.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000,2.000000

GIVES THE COLUMN NAMES IN THE DATASET

In [9]:
df.columns.tolist()

['Checking_Status',
 'Duration_Months',
 'Credit_History',
 'Purpose',
 'Credit_Amount',
 'Savings_Status',
 'Employment_Since',
 'Installment_Rate',
 'Personal_Status_Sex',
 'Other_Debtors_Guarantors',
 'Residence_Since',
 'Property',
 'Age',
 'Other_Installment_Plans',
 'Housing',
 'Existing_Credits',
 'Job',
 'Dependents',
 'Telephone',
 'Foreign_Worker',
 'Credit_Risk']

GIVES DATATYPE OF EACH COLUMN NAME

In [10]:
df.dtypes

Checking_Status             object
Duration_Months              int64
Credit_History              object
Purpose                     object
Credit_Amount                int64
Savings_Status              object
Employment_Since            object
Installment_Rate             int64
Personal_Status_Sex         object
Other_Debtors_Guarantors    object
Residence_Since              int64
Property                    object
Age                          int64
Other_Installment_Plans     object
Housing                     object
Existing_Credits             int64
Job                         object
Dependents                   int64
Telephone                   object
Foreign_Worker              object
Credit_Risk                  int64
dtype: object

DESCRIPTIVE STATISTICS

In [11]:
#used to give basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Checking_Status           1000 non-null   object
 1   Duration_Months           1000 non-null   int64
 2   Credit_History            1000 non-null   object
 3   Purpose                   1000 non-null   object
 4   Credit_Amount             1000 non-null   int64
 5   Savings_Status            1000 non-null   object
 6   Employment_Since          1000 non-null   object
 7   Installment_Rate          1000 non-null   int64
 8   Personal_Status_Sex       1000 non-null   object
 9   Other_Debtors_Guarantors  1000 non-null   object
 10  Residence_Since           1000 non-null   int64
 11  Property                  1000 non-null   object
 12  Age                       1000 non-null   int64
 13  Other_Installment_Plans   1000 non-null   object
 14  Housing                   1000 non-null   object
 15  Existing_Credits          1000 non-null   int64
 16  Job                       1000 non-null   object
 17  Dependents                1000 non-null   int64
 18  Telephone                 1000 non-null   object
 19  Foreign_Worker            1000 non-null   object
 20  Credit_Risk               1000 non-null   int64
dtypes: int64(8), object(13)
memory usage: 164.2+ KB

FINDS MISSING VALUES

In [12]:
#used to find missing values in each column
df.isnull().sum()

Checking_Status             0
Duration_Months             0
Credit_History              0
Purpose                     0
Credit_Amount               0
Savings_Status              0
Employment_Since            0
Installment_Rate            0
Personal_Status_Sex         0
Other_Debtors_Guarantors    0
Residence_Since             0
Property                    0
Age                         0
Other_Installment_Plans     0
Housing                     0
Existing_Credits            0
Job                         0
Dependents                  0
Telephone                   0
Foreign_Worker              0
Credit_Risk                 0
dtype: int64

CHECKS FOR DUPLICATE

In [13]:
#used to find duplicate values in the dataset
df.duplicated().sum()

np.int64(0)

In [14]:
#used to drop the duplicate values from the dataset
df.drop_duplicates()

,Checking_Status,Duration_Months,Credit_History,Purpose,Credit_Amount,Savings_Status,Employment_Since,Installment_Rate,Personal_Status_Sex,Other_Debtors_Guarantors,...,Property,Age,Other_Installment_Plans,Housing,Existing_Credits,Job,Dependents,Telephone,Foreign_Worker,Credit_Risk
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A14,12,A32,A42,1736,A61,A74,3,A92,A101,...,A121,31,A143,A152,1,A172,1,A191,A201,1
996,A11,30,A32,A41,3857,A61,A73,4,A91,A101,...,A122,40,A143,A152,1,A174,1,A192,A201,1
997,A14,12,A32,A43,804,A61,A75,4,A93,A101,...,A123,38,A143,A152,1,A173,1,A191,A201,1
998,A11,45,A32,A43,1845,A61,A73,4,A93,A101,...,A124,23,A143,A153,1,A173,1,A192,A201,2
999,A12,45,A34,A41,4576,A62,A71,3,A93,A101,...,A123,27,A143,A152,1,A173,1,A191,A201,1

In [15]:
expected_columns = [
    'Checking_Status',
    'Duration_Months',
    'Credit_History',
    'Purpose',
    'Credit_Amount',
    'Savings_Status',
    'Employment_Since',
    'Installment_Rate',
    'Personal_Status_Sex',
    'Other_Debtors_Guarantors',
    'Residence_Since',
    'Property',
    'Age',
    'Other_Installment_Plans',
    'Housing',
    'Existing_Credits',
    'Job',
    'Dependents',
    'Telephone',
    'Foreign_Worker',
    'Credit_Risk'
]

print("Number of columns:", len(df.columns))

print("Missing expected columns:",
      set(expected_columns) - set(df.columns))

Number of columns: 21
Missing expected columns: set()

CHECKS FOR NUMERICAL COLUMNS

In [16]:
numeric_columns = [
    'Duration_Months',
    'Credit_Amount',
    'Installment_Rate',
    'Residence_Since',
    'Age',
    'Existing_Credits',
    'Dependents'
]

print(df[numeric_columns].describe())

       Duration_Months  Credit_Amount  Installment_Rate  Residence_Since  \
count      1000.000000    1000.000000       1000.000000      1000.000000
mean         20.903000    3271.258000          2.973000         2.845000
std          12.058814    2822.736876          1.118715         1.103718
min           4.000000     250.000000          1.000000         1.000000
25%          12.000000    1365.500000          2.000000         2.000000
50%          18.000000    2319.500000          3.000000         3.000000
75%          24.000000    3972.250000          4.000000         4.000000
max          72.000000   18424.000000          4.000000         4.000000

               Age  Existing_Credits   Dependents
count  1000.000000       1000.000000  1000.000000
mean     35.546000          1.407000     1.155000
std      11.375469          0.577654     0.362086
min      19.000000          1.000000     1.000000
25%      27.000000          1.000000     1.000000
50%      33.000000          1.000000     1.000000
75%      42.000000          2.000000     1.000000
max      75.000000          4.000000     2.000000

CHECKS FOR IMPOSSIBLE AGE

In [45]:
print("Age below 18:", (df['Age'] < 18).sum())
print("Age above 100:", (df['Age'] > 100).sum())

Age below 18: 0
Age above 100: 0

CHECKS FOR INVALID CREDIT AMOUNT

In [18]:
print("Credit amount <= 0:",
      (df['Credit_Amount'] <= 0).sum())

Credit amount <= 0: 0

CHECKS FOR INVALID DURATION

In [19]:
print("Duration <= 0:",
      (df['Duration_Months'] <= 0).sum())

Duration <= 0: 0

CHECKS FOR OUTLIERS

IQR METHOD

In [20]:
def find_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower) |
        (data[column] > upper)
    ]

    return outliers, lower, upper

In [21]:
for col in ['Credit_Amount', 'Duration_Months', 'Age']:
    outliers, lower, upper = find_outliers(df, col)

    print("\nColumn:", col)
    print("Lower limit:", lower)
    print("Upper limit:", upper)
    print("Number of outliers:", len(outliers))

Column: Credit_Amount
Lower limit: -2544.625
Upper limit: 7882.375
Number of outliers: 72

Column: Duration_Months
Lower limit: -6.0
Upper limit: 42.0
Number of outliers: 70

Column: Age
Lower limit: 4.5
Upper limit: 64.5
Number of outliers: 23

SEPARATES FEATURES AND TARGET

In [22]:
X = df.drop('Credit_Risk', axis=1)

y = df['Credit_Risk']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (1000, 20)
Target shape: (1000,)

SPLITTING TRAIN AND TEST SET

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (800, 20)
Testing data: (200, 20)

IDENTIFYING CATEGORICAL VARIABLES

In [24]:
categorical_columns = X_train.select_dtypes(
    include=['object']
).columns

print("Categorical columns:")
print(list(categorical_columns))

Categorical columns:
['Checking_Status', 'Credit_History', 'Purpose', 'Savings_Status', 'Employment_Since', 'Personal_Status_Sex', 'Other_Debtors_Guarantors', 'Property', 'Other_Installment_Plans', 'Housing', 'Job', 'Telephone', 'Foreign_Worker']

IDENTIFYING NUMERICAL VARIABLES

In [25]:
numerical_columns = X_train.select_dtypes(
    include=['int64', 'float64']
).columns

print("Numerical columns:")
print(list(numerical_columns))

Numerical columns:
['Duration_Months', 'Credit_Amount', 'Installment_Rate', 'Residence_Since', 'Age', 'Existing_Credits', 'Dependents']

SCALING AND ONE HOT ENCODING

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_columns),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_columns)
    ]
)

PREVENTS DATA LEAKAGE

In [27]:
#fit → learns the required information from the training data
#transform → applies scaling and one-hot encoding to the training data
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print("Training data processed successfully")
print("Testing data processed successfully")

Training data processed successfully
Testing data processed successfully

CONVERTS PROCESSED DATA INTO DATAFRAMES

In [28]:
#converts the processed data back into a Pandas DataFrame and gives the columns proper names.
# 61 columns because one hot encoding has expanded the categorical columns
feature_names = preprocessor.get_feature_names_out()

X_train_processed = pd.DataFrame(
    X_train_processed,
    columns=feature_names
)

X_test_processed = pd.DataFrame(
    X_test_processed,
    columns=feature_names
)

print("Processed training data:", X_train_processed.shape)
print("Processed testing data:", X_test_processed.shape)

Processed training data: (800, 61)
Processed testing data: (200, 61)

SAVING TEST AND TRAIN FILES

In [29]:
import os

print(os.getcwd())

/content

In [30]:
import os
import pandas as pd

# Create processed folder
os.makedirs("data/processed", exist_ok=True)

# Add target column
train_data = X_train_processed.copy()
train_data["Credit_Risk"] = y_train.values

test_data = X_test_processed.copy()
test_data["Credit_Risk"] = y_test.values

# Save files
train_data.to_csv("data/processed/train.csv", index=False)
test_data.to_csv("data/processed/test.csv", index=False)

print("Train and test files saved successfully!")

Train and test files saved successfully!

In [31]:
print(os.listdir("data/processed"))

['test.csv', 'train.csv']

QUALITY LOG

In [32]:
#A Quality Log is basically a record of all the checks you performed on your dataset before giving it to the Machine Learning team.
quality_log = pd.DataFrame({
    'Check': [
        'Number of rows',
        'Number of columns',
        'Missing values',
        'Duplicate rows',
        'Training Set',
        'Testing  Set'
    ],
    'Result': [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(X_train),
        len(X_test)
    ]
})

print(quality_log)

               Check  Result
0     Number of rows    1000
1  Number of columns      21
2     Missing values       0
3     Duplicate rows       0
4       Training Set     800
5       Testing  Set     200

SAVING DATA QUALITY LOG

In [33]:
quality_log.to_csv(
    "data/processed/data_quality_log.csv",
    index=False
)

print("Data quality log saved!")

Data quality log saved!

LOADING CLEANED DATA

In [34]:
import pandas as pd

train_data = pd.read_csv("/content/data/processed/train.csv")
test_data = pd.read_csv("/content/data/processed/test.csv")

In [35]:
train_data

,num__Duration_Months,num__Credit_Amount,num__Installment_Rate,num__Residence_Since,num__Age,num__Existing_Credits,num__Dependents,cat__Checking_Status_A11,cat__Checking_Status_A12,cat__Checking_Status_A13,...,cat__Housing_A153,cat__Job_A171,cat__Job_A172,cat__Job_A173,cat__Job_A174,cat__Telephone_A191,cat__Telephone_A192,cat__Foreign_Worker_A201,cat__Foreign_Worker_A202,Credit_Risk
0,1.289592,1.925766,0.052281,1.053413,1.057784,-0.718745,-0.436436,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,2
1,-0.742595,-0.892853,0.942164,1.053413,0.242449,-0.718745,-0.436436,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1
2,1.289592,0.816433,0.052281,-0.747293,-0.663479,1.045047,-0.436436,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1
3,1.289592,0.299568,0.052281,-0.747293,-0.572886,-0.718745,-0.436436,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
4,2.305686,1.982655,-1.727486,-0.747293,-1.025850,-0.718745,-0.436436,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,-1.250642,-0.730794,-1.727486,-1.647646,-0.754072,1.045047,-0.436436,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1
796,0.273499,-0.694864,0.942164,-0.747293,0.695413,1.045047,2.291288,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,2
797,-0.234548,-0.252479,0.052281,1.053413,0.695413,-0.718745,-0.436436,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1
798,-0.234548,1.976667,-1.727486,-0.747293,-1.116443,1.045047,-0.436436,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1
799,-0.488572,-0.060104,-0.837603,-0.747293,-0.210515,-0.718745,-0.436436,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1

In [36]:
test_data

,num__Duration_Months,num__Credit_Amount,num__Installment_Rate,num__Residence_Since,num__Age,num__Existing_Credits,num__Dependents,cat__Checking_Status_A11,cat__Checking_Status_A12,cat__Checking_Status_A13,...,cat__Housing_A153,cat__Job_A171,cat__Job_A172,cat__Job_A173,cat__Job_A174,cat__Telephone_A191,cat__Telephone_A192,cat__Foreign_Worker_A201,cat__Foreign_Worker_A202,Credit_Risk
0,-0.234548,-0.477788,0.052281,0.153060,0.061263,-0.718745,-0.436436,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1
1,-0.742595,-0.497625,0.942164,-0.747293,-0.119922,1.045047,-0.436436,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1
2,0.273499,-0.810513,0.942164,1.053413,1.148377,-0.718745,-0.436436,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,2
3,-0.234548,-0.032034,0.052281,-1.647646,-0.391701,-0.718745,-0.436436,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1
4,0.527522,-0.250607,0.942164,-0.747293,-1.116443,1.045047,-0.436436,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2.305686,1.470655,0.052281,1.053413,1.601341,1.045047,2.291288,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,2
196,-0.234548,-0.285414,0.942164,-0.747293,0.604820,1.045047,-0.436436,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1
197,-0.742595,-0.721437,0.052281,-0.747293,-0.935257,-0.718745,-0.436436,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1
198,0.781545,1.182843,0.942164,1.053413,-0.391701,-0.718745,-0.436436,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,2
199,0.019475,-0.598303,0.942164,0.153060,-0.119922,1.045047,-0.436436,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1

In [37]:
import os

os.makedirs("data/processed", exist_ok=True)

X_train_processed.to_csv(
    "data/processed/X_train_processed.csv",
    index=False
)

print("Training CSV saved successfully!")

Training CSV saved successfully!

In [38]:
X_test_processed.to_csv(
    "data/processed/X_test_processed.csv",
    index=False
)

print("Testing CSV saved successfully!")

Testing CSV saved successfully!

In [39]:
import os

print(os.listdir("data/processed"))

['X_test_processed.csv', 'test.csv', 'X_train_processed.csv', 'data_quality_log.csv', 'train.csv']

In [40]:
import shutil
from google.colab import files

shutil.make_archive("cleaned_credit_data", "zip", "data/processed")

files.download("cleaned_credit_data.zip")